name: Deploy Next.js App

on:
  push:
    branches:
      - main # Se activa cuando haces push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Desplegar vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          command_timeout: 30m 
          port: ${{ secrets.PORT }}
          script: |
            cd ~/tickets-geniorama 
            git pull origin main

            # 3. CARGA DIRECTA DE BINARIOS
            # Esto agrega la versión específica de Node directamente al PATH
            export NVM_DIR="/home/ubuntu/.nvm"
            export PATH="$NVM_DIR/versions/node/v22.13.1/bin:$PATH"
            
            # Verificación inmediata
            node -v
            npm -v

            # 4. Instalar y Compilar
            npm install
            NODE_OPTIONS="--max-old-space-size=1536" npm run build

            # 5. Reiniciar con PM2 usando la ruta completa para evitar fallos
            # Cargamos PM2 si no está en el PATH
            export PATH="$PATH:$(npm config get prefix)/bin"
            pm2 restart mi-next-app || pm2 start npm --name "mi-next-app" -- start